name = "unstablelabstore"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "unstable-store-db"
database_id = "8c08d5b9-b928-457d-93f0-c8cefdc95bac"
